name: Release Binaries

on:
  release:
    types: [published]
    paths:
      - 'cmd/**'
      - 'pkg/**'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.34
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.19.2.linux-amd64.tar.gz"
          project_path: "./cmd"
          binary_name: "kubectl-esopmok"
          extra_files: LICENSE README.md
